before_install:
- openssl aes-256-cbc -K $encrypted_a384211934a8_key -iv $encrypted_a384211934a8_iv
  -in deploykey.enc -out ./deploykey -d
- ssh-add ./deploykey
- eval "$(ssh-agent -s)"
- chmod 600 ./deploy_key
- echo -e "Host $SERVER_IP_ADDRESS\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
- ssh-add ./deploy_key
# test ssh connection for: https://github.com/dwyl/learn-travis/issues/42
- ssh -i ./deploykey travis@schaapkabap.nl pwd
