before_install:
- openssl aes-256-cbc -K $encrypted_a384211934a8_key -iv $encrypted_a384211934a8_iv
  -in deploy_key.enc -out ./deploy_key -d
- chmod 400 ./deploy_key
- ssh-add ./deploy_key
- eval "$(ssh-agent -s)"
- chmod 600 ./deploy_key
- echo -e "Host $SERVER_IP_ADDRESS\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
- ssh-add ./deploy_key
- ssh -i ./deploy_key travis@schaapkabap.nl pwd
