apiName: "Alexanders API"

database:
  driverClass: org.postgresql.Driver
  user: albert_api
  password: albert
  url: jdbc:postgresql://localhost:5432/iprwc
  properties:
    charSet: UTF-8
  maxWaitForConnection: 1s
  minSize: 8
  maxSize: 32
  checkConnectionWhileIdle: false
  evictionInterval: 10s
  minIdleTime: 1 minute

logging:
  level: INFO
  loggers:
    main.app: DEBUG
    org.hibernate.SQL:
      level: DEBUG

assets:
  mappings:
    /assets: /
  overrides:
    /: ../frontend/

server:
  applicationContextPath: /
  rootPath: /api/*
  adminContextPath: /admin/*
  applicationConnectors:
    - type: http
      port: 8080

